let strip : neopixel.Strip = null
let range_1 : neopixel.Strip = null
let range_2 : neopixel.Strip = null
let range_3 : neopixel.Strip = null
let range_4 : neopixel.Strip = null
let range_5 : neopixel.Strip = null
let range_6 : neopixel.Strip = null
let range_7 : neopixel.Strip = null
let range_8 : neopixel.Strip = null
let range_9 : neopixel.Strip = null
let range_10 : neopixel.Strip = null
let range_11 : neopixel.Strip = null
let range_12 : neopixel.Strip = null
let range_13 : neopixel.Strip = null
let range_14 : neopixel.Strip = null
let range_15 : neopixel.Strip = null
let range_16 : neopixel.Strip = null
let range_17 : neopixel.Strip = null
let range_18 : neopixel.Strip = null
let range_19 : neopixel.Strip = null
let range_20 : neopixel.Strip = null
let range_21 : neopixel.Strip = null
let range_22 : neopixel.Strip = null
let range_23 : neopixel.Strip = null
let range_24 : neopixel.Strip = null
let range_25 : neopixel.Strip = null
let range_26 : neopixel.Strip = null
let range_27 : neopixel.Strip = null
let range_28 : neopixel.Strip = null
let range_29 : neopixel.Strip = null
let range_30 : neopixel.Strip = null
input.onButtonPressed(Button.A, function on_button_pressed_a() {
    
    strip = neopixel.create(DigitalPin.P0, 30, NeoPixelMode.RGB)
    basic.pause(2000)
    range_1 = strip.range(29, 1)
    range_1.setBrightness(80)
    range_1.showColor(neopixel.colors(NeoPixelColors.Purple))
    basic.pause(2000)
    range_2 = strip.range(28, 2)
    range_2.setBrightness(80)
    range_2.showColor(neopixel.colors(NeoPixelColors.Purple))
    basic.pause(2000)
    range_3 = strip.range(27, 3)
    range_3.setBrightness(80)
    range_3.showColor(neopixel.colors(NeoPixelColors.Purple))
    basic.pause(2000)
    range_4 = strip.range(26, 4)
    range_4.setBrightness(80)
    range_4.showColor(neopixel.colors(NeoPixelColors.Purple))
    basic.pause(2000)
    range_5 = strip.range(25, 5)
    range_5.setBrightness(80)
    range_5.showColor(neopixel.colors(NeoPixelColors.Purple))
    basic.pause(2000)
    range_6 = strip.range(24, 6)
    range_6.setBrightness(80)
    range_6.showColor(neopixel.colors(NeoPixelColors.Indigo))
    basic.pause(2000)
    range_7 = strip.range(23, 7)
    range_7.setBrightness(80)
    range_7.showColor(neopixel.colors(NeoPixelColors.Indigo))
    basic.pause(2000)
    range_8 = strip.range(22, 8)
    range_8.setBrightness(80)
    range_8.showColor(neopixel.colors(NeoPixelColors.Indigo))
    basic.pause(2000)
    range_9 = strip.range(21, 9)
    range_9.setBrightness(80)
    range_9.showColor(neopixel.colors(NeoPixelColors.Indigo))
    basic.pause(2000)
    range_10 = strip.range(20, 10)
    range_10.setBrightness(80)
    range_10.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(2000)
    range_11 = strip.range(19, 11)
    range_11.setBrightness(80)
    range_11.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(2000)
    range_12 = strip.range(18, 12)
    range_12.setBrightness(80)
    range_12.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(2000)
    range_13 = strip.range(17, 13)
    range_13.setBrightness(80)
    range_13.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(2000)
    range_14 = strip.range(16, 14)
    range_14.setBrightness(80)
    range_14.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(2000)
    range_15 = strip.range(15, 15)
    range_15.setBrightness(80)
    range_15.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(2000)
    range_16 = strip.range(14, 16)
    range_16.setBrightness(80)
    range_16.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(2000)
    range_17 = strip.range(13, 17)
    range_17.setBrightness(80)
    range_17.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(2000)
    range_18 = strip.range(12, 18)
    range_18.setBrightness(80)
    range_18.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(2000)
    range_19 = strip.range(11, 19)
    range_19.setBrightness(80)
    range_19.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(2000)
    range_20 = strip.range(10, 20)
    range_20.setBrightness(80)
    range_20.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(2000)
    range_21 = strip.range(9, 21)
    range_21.setBrightness(80)
    range_21.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(2000)
    range_22 = strip.range(8, 22)
    range_22.setBrightness(80)
    range_22.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(2000)
    range_23 = strip.range(7, 23)
    range_23.setBrightness(80)
    range_23.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(2000)
    range_24 = strip.range(6, 24)
    range_24.setBrightness(80)
    range_24.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(2000)
    range_25 = strip.range(5, 25)
    range_25.setBrightness(80)
    range_25.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(2000)
    range_26 = strip.range(4, 26)
    range_26.setBrightness(80)
    range_26.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(2000)
    range_27 = strip.range(3, 27)
    range_27.setBrightness(80)
    range_27.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(2000)
    range_28 = strip.range(2, 28)
    range_28.setBrightness(80)
    range_28.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(2000)
    range_29 = strip.range(1, 29)
    range_29.setBrightness(80)
    range_29.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(2000)
    range_30 = strip.range(0, 30)
    range_30.setBrightness(80)
    range_30.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(15000)
    strip = neopixel.create(DigitalPin.P0, 30, NeoPixelMode.RGB)
    strip.show()
    strip.clear()
})
input.onButtonPressed(Button.B, function on_button_pressed_b() {
    
    strip = neopixel.create(DigitalPin.P0, 30, NeoPixelMode.RGB)
    basic.pause(2000)
    range_7 = strip.range(25, 5)
    range_7.setBrightness(80)
    range_7.showColor(neopixel.colors(NeoPixelColors.Purple))
    basic.pause(4000)
    range_6 = strip.range(21, 9)
    range_6.setBrightness(80)
    range_6.showColor(neopixel.colors(NeoPixelColors.Indigo))
    basic.pause(4000)
    range_5 = strip.range(17, 13)
    range_5.setBrightness(80)
    range_5.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(4000)
    range_4 = strip.range(13, 17)
    range_4.setBrightness(80)
    range_4.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(4000)
    range_3 = strip.range(9, 21)
    range_3.setBrightness(80)
    range_3.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(4000)
    range_2 = strip.range(5, 25)
    range_2.setBrightness(80)
    range_2.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(4000)
    range_1 = strip.range(0, 30)
    range_1.setBrightness(80)
    range_1.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(15000)
    strip = neopixel.create(DigitalPin.P0, 30, NeoPixelMode.RGB)
    strip.show()
    strip.clear()
})
