strip: neopixel.Strip = None
range_1: neopixel.Strip = None
range_2: neopixel.Strip = None
range_3: neopixel.Strip = None
range_4: neopixel.Strip = None
range_5: neopixel.Strip = None
range_6: neopixel.Strip = None
range_7: neopixel.Strip = None
range_8: neopixel.Strip = None
range_9: neopixel.Strip = None
range_10: neopixel.Strip = None
range_11: neopixel.Strip = None
range_12: neopixel.Strip = None
range_13: neopixel.Strip = None
range_14: neopixel.Strip = None
range_15: neopixel.Strip = None
range_16: neopixel.Strip = None
range_17: neopixel.Strip = None
range_18: neopixel.Strip = None
range_19: neopixel.Strip = None
range_20: neopixel.Strip = None
range_21: neopixel.Strip = None
range_22: neopixel.Strip = None
range_23: neopixel.Strip = None
range_24: neopixel.Strip = None
range_25: neopixel.Strip = None
range_26: neopixel.Strip = None
range_27: neopixel.Strip = None
range_28: neopixel.Strip = None
range_29: neopixel.Strip = None
range_30: neopixel.Strip = None

def on_button_pressed_a():
    global strip, range_1, range_2, range_3, range_4, range_5, range_6, range_7, range_8, range_9, range_10, range_11, range_12, range_13, range_14, range_15, range_16, range_17, range_18, range_19, range_20, range_21, range_22, range_23, range_24, range_25, range_26, range_27, range_28, range_29, range_30
    strip = neopixel.create(DigitalPin.P0, 30, NeoPixelMode.RGB)
    basic.pause(2000)
    range_1 = strip.range(29, 1)
    range_1.set_brightness(80)
    range_1.show_color(neopixel.colors(NeoPixelColors.PURPLE))
    basic.pause(2000)
    range_2 = strip.range(28, 2)
    range_2.set_brightness(80)
    range_2.show_color(neopixel.colors(NeoPixelColors.PURPLE))
    basic.pause(2000)
    range_3 = strip.range(27, 3)
    range_3.set_brightness(80)
    range_3.show_color(neopixel.colors(NeoPixelColors.PURPLE))
    basic.pause(2000)
    range_4 = strip.range(26, 4)
    range_4.set_brightness(80)
    range_4.show_color(neopixel.colors(NeoPixelColors.PURPLE))
    basic.pause(2000)
    range_5 = strip.range(25, 5)
    range_5.set_brightness(80)
    range_5.show_color(neopixel.colors(NeoPixelColors.PURPLE))
    basic.pause(2000)
    range_6 = strip.range(24, 6)
    range_6.set_brightness(80)
    range_6.show_color(neopixel.colors(NeoPixelColors.INDIGO))
    basic.pause(2000)
    range_7 = strip.range(23, 7)
    range_7.set_brightness(80)
    range_7.show_color(neopixel.colors(NeoPixelColors.INDIGO))
    basic.pause(2000)
    range_8 = strip.range(22, 8)
    range_8.set_brightness(80)
    range_8.show_color(neopixel.colors(NeoPixelColors.INDIGO))
    basic.pause(2000)
    range_9 = strip.range(21, 9)
    range_9.set_brightness(80)
    range_9.show_color(neopixel.colors(NeoPixelColors.INDIGO))
    basic.pause(2000)
    range_10 = strip.range(20, 10)
    range_10.set_brightness(80)
    range_10.show_color(neopixel.colors(NeoPixelColors.BLUE))
    basic.pause(2000)
    range_11 = strip.range(19, 11)
    range_11.set_brightness(80)
    range_11.show_color(neopixel.colors(NeoPixelColors.BLUE))
    basic.pause(2000)
    range_12 = strip.range(18, 12)
    range_12.set_brightness(80)
    range_12.show_color(neopixel.colors(NeoPixelColors.BLUE))
    basic.pause(2000)
    range_13 = strip.range(17, 13)
    range_13.set_brightness(80)
    range_13.show_color(neopixel.colors(NeoPixelColors.BLUE))
    basic.pause(2000)
    range_14 = strip.range(16, 14)
    range_14.set_brightness(80)
    range_14.show_color(neopixel.colors(NeoPixelColors.GREEN))
    basic.pause(2000)
    range_15 = strip.range(15, 15)
    range_15.set_brightness(80)
    range_15.show_color(neopixel.colors(NeoPixelColors.GREEN))
    basic.pause(2000)
    range_16 = strip.range(14, 16)
    range_16.set_brightness(80)
    range_16.show_color(neopixel.colors(NeoPixelColors.GREEN))
    basic.pause(2000)
    range_17 = strip.range(13, 17)
    range_17.set_brightness(80)
    range_17.show_color(neopixel.colors(NeoPixelColors.GREEN))
    basic.pause(2000)
    range_18 = strip.range(12, 18)
    range_18.set_brightness(80)
    range_18.show_color(neopixel.colors(NeoPixelColors.YELLOW))
    basic.pause(2000)
    range_19 = strip.range(11, 19)
    range_19.set_brightness(80)
    range_19.show_color(neopixel.colors(NeoPixelColors.YELLOW))
    basic.pause(2000)
    range_20 = strip.range(10, 20)
    range_20.set_brightness(80)
    range_20.show_color(neopixel.colors(NeoPixelColors.YELLOW))
    basic.pause(2000)
    range_21 = strip.range(9, 21)
    range_21.set_brightness(80)
    range_21.show_color(neopixel.colors(NeoPixelColors.YELLOW))
    basic.pause(2000)
    range_22 = strip.range(8, 22)
    range_22.set_brightness(80)
    range_22.show_color(neopixel.colors(NeoPixelColors.ORANGE))
    basic.pause(2000)
    range_23 = strip.range(7, 23)
    range_23.set_brightness(80)
    range_23.show_color(neopixel.colors(NeoPixelColors.ORANGE))
    basic.pause(2000)
    range_24 = strip.range(6, 24)
    range_24.set_brightness(80)
    range_24.show_color(neopixel.colors(NeoPixelColors.ORANGE))
    basic.pause(2000)
    range_25 = strip.range(5, 25)
    range_25.set_brightness(80)
    range_25.show_color(neopixel.colors(NeoPixelColors.ORANGE))
    basic.pause(2000)
    range_26 = strip.range(4, 26)
    range_26.set_brightness(80)
    range_26.show_color(neopixel.colors(NeoPixelColors.RED))
    basic.pause(2000)
    range_27 = strip.range(3, 27)
    range_27.set_brightness(80)
    range_27.show_color(neopixel.colors(NeoPixelColors.RED))
    basic.pause(2000)
    range_28 = strip.range(2, 28)
    range_28.set_brightness(80)
    range_28.show_color(neopixel.colors(NeoPixelColors.RED))
    basic.pause(2000)
    range_29 = strip.range(1, 29)
    range_29.set_brightness(80)
    range_29.show_color(neopixel.colors(NeoPixelColors.RED))
    basic.pause(2000)
    range_30 = strip.range(0, 30)
    range_30.set_brightness(80)
    range_30.show_color(neopixel.colors(NeoPixelColors.RED))
    basic.pause(15000)
    strip = neopixel.create(DigitalPin.P0, 30, NeoPixelMode.RGB)
    strip.show()
    strip.clear()
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_button_pressed_b():
    global strip, range_7, range_6, range_5, range_4, range_3, range_2, range_1
    strip = neopixel.create(DigitalPin.P0, 30, NeoPixelMode.RGB)
    basic.pause(2000)
    range_7 = strip.range(25, 5)
    range_7.set_brightness(80)
    range_7.show_color(neopixel.colors(NeoPixelColors.PURPLE))
    basic.pause(4000)
    range_6 = strip.range(21, 9)
    range_6.set_brightness(80)
    range_6.show_color(neopixel.colors(NeoPixelColors.INDIGO))
    basic.pause(4000)
    range_5 = strip.range(17, 13)
    range_5.set_brightness(80)
    range_5.show_color(neopixel.colors(NeoPixelColors.BLUE))
    basic.pause(4000)
    range_4 = strip.range(13, 17)
    range_4.set_brightness(80)
    range_4.show_color(neopixel.colors(NeoPixelColors.GREEN))
    basic.pause(4000)
    range_3 = strip.range(9, 21)
    range_3.set_brightness(80)
    range_3.show_color(neopixel.colors(NeoPixelColors.YELLOW))
    basic.pause(4000)
    range_2 = strip.range(5, 25)
    range_2.set_brightness(80)
    range_2.show_color(neopixel.colors(NeoPixelColors.ORANGE))
    basic.pause(4000)
    range_1 = strip.range(0, 30)
    range_1.set_brightness(80)
    range_1.show_color(neopixel.colors(NeoPixelColors.RED))
    basic.pause(15000)
    strip = neopixel.create(DigitalPin.P0, 30, NeoPixelMode.RGB)
    strip.show()
    strip.clear()
input.on_button_pressed(Button.B, on_button_pressed_b)
